# Generated by Django 3.2.6 on 2021-08-07 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201208_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
