# Generated by Django 3.2.6 on 2021-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
